In [1]:
__author__ = 'pbj00812@gmail.com'

In [2]:
import numpy as np
import cv2

In [5]:
def makeKernel():
    M1 = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
    M2 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    M3 = cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))
    
    print('M1')
    print(M1)
    print('M2')
    print(M2)
    print('M3')
    print(M3)

In [6]:
makeKernel()

M1
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
M2
[[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]
M3
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
