In [1]:
__author__ = 'pbj00812@gmail.com'

In [2]:
import numpy as np
import cv2

In [3]:
def bluring():
    img = cv2.imread('car.jpg')
    
    kernel = np.ones((5, 5), np.float32)/25
    print(kernel)
    blur = cv2.filter2D(img, -1, kernel)
    
    cv2.imshow('original', img)
    cv2.imshow('blur', blur)
    
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [4]:
bluring()

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
